In [2]:
import pandas as pd

In [7]:
df = pd.read_csv("data/offshore_wind_cable_market.csv")
df

   Year  Market_Size_USD_Billion Classification  YoY_Growth_Percent
0  2023                    4.049     Historical                 NaN
1  2024                    4.627     Historical               14.29
2  2025                    5.320      Base Year               14.97
3  2026                    6.321       Forecast               18.81
4  2027                    7.046       Forecast               11.48

In [8]:
df["Calculated_YoY_%"] = (
    df["Market_Size_USD_Billion"]
    .pct_change()
    * 100
)

df["Calculated_YoY_%"] = df["Calculated_YoY_%"].round(2)

df

,Year,Market_Size_USD_Billion,Classification,YoY_Growth_Percent,Calculated_YoY_%
0,2023,4.049,Historical,NaN,NaN
1,2024,4.627,Historical,14.29,14.28
2,2025,5.320,Base Year,14.97,14.98
3,2026,6.321,Forecast,18.81,18.82
4,2027,7.046,Forecast,11.48,11.47

In [9]:
start_value = df.loc[df["Year"] == 2023, "Market_Size_USD_Billion"].iloc[0]
end_value = df.loc[df["Year"] == 2027, "Market_Size_USD_Billion"].iloc[0]

years = 4

cagr_2023_2027 = ((end_value / start_value) ** (1 / years) - 1) * 100

print(f"2023–2027 CAGR: {cagr_2023_2027:.2f}%")

2023–2027 CAGR: 14.85%

In [10]:
summary = df[
    [
        "Year",
        "Market_Size_USD_Billion",
        "Classification",
        "Calculated_YoY_%"
    ]
].copy()

summary

   Year  Market_Size_USD_Billion Classification  Calculated_YoY_%
0  2023                    4.049     Historical               NaN
1  2024                    4.627     Historical             14.28
2  2025                    5.320      Base Year             14.98
3  2026                    6.321       Forecast             18.82
4  2027                    7.046       Forecast             11.47

## Key Findings

- Global offshore wind cable market size increases from USD 4.049B in 2023 to USD 7.046B in 2027.
- 2025 is treated as the Base Year.
- 2026 and 2027 are forecast values from the same source.
- The strongest annual growth in the selected period occurs between 2025 and 2026.
- The calculated 2023–2027 CAGR is approximately 14.86%.
- The source-reported long-term CAGR for 2025–2032 is 15.96%.
- This dataset is used as a proxy for subsea power cable demand growth, not as a complete measure of the entire subsea power cable market.